### ISSUE TITLE
help with phpstorm xdebug conf

### ISSUE THREAD

**Issue by apoberez** [linuxjuggler/php-7.2-xdebug-alpine#1]
Hi, can you provide your approach to configure phpstorm with this xdebug setting. Actually I had apply some changes to make it work with remote debug in ide:
xdebug.remote_host=172.17.0.1
xdebug.remote_autostart=on

Maybe you can help me make it better, thanks.

**Comment by zaherg** [comment]
hey @apoberez , I'll try to record a video in the next few days showing how I use xdebug with my images using PHPStorm on mac.

sorry for being late, but I just noticed your comment.

**Comment by zaherg** [comment]
hey @apoberez am really sorry for the delay, but can you check https://serversforhackers.com/c/getting-xdebug-working as it is some how the same with my docker image.

thanks
